filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"
          - decode_json_fields:        # <-- Add this processor
              fields: ["message"]      # The field that contains the JSON string
              target: ""               # Merge the decoded JSON fields into the root of the event
              overwrite_keys: true     # Overwrite existing keys if there are conflicts
    output.logstash:
      hosts: ["logstash-logstash:5044"]