apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: application-ingressroute
  namespace: model-serving
  labels:
    app.kubernetes.io/name: demand-forecasting
    app.kubernetes.io/instance: application
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: application
          port: 8000
