image:
  repository: docker.io/ngnquanq/demand-forecasting
  tag: v5.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

spec:
  replicas: 3

tracing:
  enabled: true
  environmentVariables:
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.tracing.svc.cluster.local:4318/v1/traces" 
    OTEL_SERVICE_NAME: "demand-forecasting-service"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=demand-forecasting-service"

ingress:
  enabled: true
  host: "34.58.254.112"