image:
  repository: docker.io/ngnquanq/demand-forecasting
  tag: latest
  pullPolicy: Always

persistence:
  logs:
    enabled: true
    storageClass: "standard" 
    size: 2Gi

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000
